# Site Settings
title: ZUM 기술 블로그
email: zuminternet@zuminternet.com
description: "생각을 읽다, ZUM, 고객의 생각을 읽고 담는 줌 인터넷 개발자들의 '좀 다른 개발 이야기'를 소개 합니다."
baseurl: ""
url: https://zuminternet.github.io
google_analytics: "UA-XXXXXXXX-X"

# User Settings
username: ZUM TECH BLOG
logo: /images/custom/img_zum_logo_white.png
logo_simple: /images/custom/img_zum_z_white.png
catchphrase: 생각을 읽다

# OG Tag
og_type: website
og_url: https://zuminternet.github.io/
og_image: http://lego.zumst.com/resources/current/images/thumb_zum.jpg


# Social Media
# Remove the item if you don't need it
github_username: zuminternet
facebook_username: zumcom
twitter_username: "@zum_com"
#instagram_username:
#linkedin_username:
#medium_username:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
plugins:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Contact
    url: zuminternet.com/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules', '.idea']
